/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kp_desa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author deden
 */
public class user extends javax.swing.JFrame {
    private Connection con;
    private java.sql.Statement stat;
    private DefaultTableModel model;
    /**
     * Creates new form user
     */
     public user() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;

        String judul[] = {"Member", "Nama", "Waktu", "Tanggal", "Hari", "Harga"};
        model = new DefaultTableModel(judul, 0);
       
    }








    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        member = new javax.swing.JRadioButton();
        tidak = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        waktu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hari = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        harga1 = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(865, 515));
        setPreferredSize(new java.awt.Dimension(600, 723));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setText("MARI INPUT KAN DIRI ANDA !!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 30, 380, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 121, 0, 0);

        member.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        member.setText("Member");
        getContentPane().add(member);
        member.setBounds(53, 169, 90, 25);

        tidak.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tidak.setText("Tidak");
        getContentPane().add(tidak);
        tidak.setBounds(150, 170, 80, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("SILAHKAN PILIH SALAH SATU ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(43, 144, 192, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("NAMA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(46, 215, 39, 16);
        getContentPane().add(nama);
        nama.setBounds(103, 212, 159, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("WAKTU ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(46, 262, 50, 16);
        getContentPane().add(waktu);
        waktu.setBounds(46, 296, 216, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("HARI ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 350, 37, 16);

        hari.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SENIN", "SELASA", "RABU", "KAMIS", "JUM'AT", "SABTU", "MINGGU" }));
        getContentPane().add(hari);
        hari.setBounds(100, 350, 161, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("HARGA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(358, 144, 46, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("(*MEMBER RP 200.000/SEMINGU 1 KALI)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(422, 144, 227, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("(*NON MEMBER RP 50.000/JAM)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(422, 173, 190, 15);
        getContentPane().add(harga1);
        harga1.setBounds(420, 210, 220, 30);

        save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(300, 430, 80, 25);

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(440, 430, 85, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("(*CONTOH 17.00 - 18.00)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(108, 262, 160, 15);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel11.setText("GOR BUMDES KEMUNING ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 70, 290, 24);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("TANGGAL");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 290, 70, 16);

        Tanggal.setMaximumSize(new java.awt.Dimension(1000, 1000));
        Tanggal.setMinimumSize(new java.awt.Dimension(965, 615));
        Tanggal.setPreferredSize(new java.awt.Dimension(995, 723));
        getContentPane().add(Tanggal);
        Tanggal.setBounds(420, 290, 220, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*Tanpa Titik");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(420, 190, 110, 13);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*contoh 2023-10-12");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(420, 270, 140, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
          try {
            String Member = "";
            if (member.isSelected()) {
                Member = "Member";
            } else if (tidak.isSelected()) {
                Member = "Tidak";
            }

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gor_db", "root", "");

            String sql = "INSERT INTO jadwal_tb (Member, Nama, Waktu,Tanggal, Hari, Harga) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = cn.prepareStatement(sql);
            preparedStatement.setString(1, Member);
            preparedStatement.setString(2, nama.getText());
            preparedStatement.setString(3, waktu.getText());
            preparedStatement.setString(4, Tanggal.getText());
            preparedStatement.setString(5, hari.getSelectedItem().toString());
            preparedStatement.setInt(6, Integer.valueOf(harga1.getText()));

            preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Input");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
            Logger.getLogger(user.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
int jawab = JOptionPane.showOptionDialog(this,
                "Apakah Ingin Logout?", 
                "Logout", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(jawab==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this,"Kamu Berhasil Logout");
         this.setVisible(false);
        new Login().setVisible(true);
        }   
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
     /* Set the Nimbus look and feel */
     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
 }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tanggal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField harga1;
    private javax.swing.JComboBox<String> hari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton member;
    private javax.swing.JTextField nama;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton tidak;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables
    
}
